### ISSUE TITLE
Broken requirements.txt

### ISSUE THREAD

**Issue by marcorosa** [Storj/python-libstorj#3]
Current requirements.txt file cannot be installed.
Package `chrome-gnome-shell` appears not to exist in pypi and `pygobject` seems to be broken.
Other packages have an outdated version that could be updated.

**Comment by bryanchriswhite** [comment]
This should be addressed by [improve devops (#2)](https://github.com/bryanchriswhite/python-libstorj/pull/2)

**Comment by marcorosa** [comment]
Fixed by #PR2 on your branch.
I'm gonna close this issue.
